# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digital_controller.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 95))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_serial = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_serial.setObjectName("label_serial")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_serial)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_iProduct = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_iProduct.sizePolicy().hasHeightForWidth())
        self.lineEdit_iProduct.setSizePolicy(sizePolicy)
        self.lineEdit_iProduct.setObjectName("lineEdit_iProduct")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_iProduct)
        self.comboBox_Mode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_Mode.setObjectName("comboBox_Mode")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_Mode)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 10, 351, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_I = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_I.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_I.setSizePolicy(sizePolicy)
        self.doubleSpinBox_I.setDecimals(3)
        self.doubleSpinBox_I.setSingleStep(0.01)
        self.doubleSpinBox_I.setObjectName("doubleSpinBox_I")
        self.gridLayout.addWidget(self.doubleSpinBox_I, 1, 1, 1, 1)
        self.pushButton_I = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_I.sizePolicy().hasHeightForWidth())
        self.pushButton_I.setSizePolicy(sizePolicy)
        self.pushButton_I.setObjectName("pushButton_I")
        self.gridLayout.addWidget(self.pushButton_I, 1, 0, 1, 1)
        self.pushButton_D = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_D.sizePolicy().hasHeightForWidth())
        self.pushButton_D.setSizePolicy(sizePolicy)
        self.pushButton_D.setObjectName("pushButton_D")
        self.gridLayout.addWidget(self.pushButton_D, 2, 0, 1, 1)
        self.pushButton_Notch = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Notch.sizePolicy().hasHeightForWidth())
        self.pushButton_Notch.setSizePolicy(sizePolicy)
        self.pushButton_Notch.setObjectName("pushButton_Notch")
        self.gridLayout.addWidget(self.pushButton_Notch, 3, 0, 1, 1)
        self.pushButton_P = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_P.sizePolicy().hasHeightForWidth())
        self.pushButton_P.setSizePolicy(sizePolicy)
        self.pushButton_P.setObjectName("pushButton_P")
        self.gridLayout.addWidget(self.pushButton_P, 0, 0, 1, 1)
        self.doubleSpinBox_D = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_D.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_D.setSizePolicy(sizePolicy)
        self.doubleSpinBox_D.setDecimals(3)
        self.doubleSpinBox_D.setSingleStep(0.01)
        self.doubleSpinBox_D.setObjectName("doubleSpinBox_D")
        self.gridLayout.addWidget(self.doubleSpinBox_D, 2, 1, 1, 1)
        self.doubleSpinBox_Notch = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Notch.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Notch.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Notch.setDecimals(3)
        self.doubleSpinBox_Notch.setSingleStep(0.01)
        self.doubleSpinBox_Notch.setObjectName("doubleSpinBox_Notch")
        self.gridLayout.addWidget(self.doubleSpinBox_Notch, 3, 1, 1, 1)
        self.doubleSpinBox_P = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_P.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_P.setSizePolicy(sizePolicy)
        self.doubleSpinBox_P.setDecimals(3)
        self.doubleSpinBox_P.setSingleStep(0.01)
        self.doubleSpinBox_P.setObjectName("doubleSpinBox_P")
        self.gridLayout.addWidget(self.doubleSpinBox_P, 0, 1, 1, 1)
        self.doubleSpinBox_Setpoint = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Setpoint.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Setpoint.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Setpoint.setDecimals(3)
        self.doubleSpinBox_Setpoint.setSingleStep(0.01)
        self.doubleSpinBox_Setpoint.setObjectName("doubleSpinBox_Setpoint")
        self.gridLayout.addWidget(self.doubleSpinBox_Setpoint, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(5, 311, 631, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 261, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Hold = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Hold.setObjectName("pushButton_Hold")
        self.horizontalLayout.addWidget(self.pushButton_Hold)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 200, 261, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumber_control = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_control.setObjectName("lcdNumber_control")
        self.gridLayout_2.addWidget(self.lcdNumber_control, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lcdNumber_output = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_output.setObjectName("lcdNumber_output")
        self.gridLayout_2.addWidget(self.lcdNumber_output, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.menuDevice.addAction(self.actionSearch)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Serial No"))
        self.label_serial.setText(_translate("MainWindow", "000000"))
        self.label_2.setText(_translate("MainWindow", "iProduct"))
        self.label_4.setText(_translate("MainWindow", "Mode"))
        self.pushButton_I.setText(_translate("MainWindow", "I"))
        self.pushButton_D.setText(_translate("MainWindow", "D"))
        self.pushButton_Notch.setText(_translate("MainWindow", "Notch Filter"))
        self.pushButton_P.setText(_translate("MainWindow", "P"))
        self.label_6.setText(_translate("MainWindow", "Setpoint"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Hold.setText(_translate("MainWindow", "Hold"))
        self.label_3.setText(_translate("MainWindow", "Control"))
        self.label_5.setText(_translate("MainWindow", "Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))

